// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWT-UqCOK_JCnu0VCsNihgcIMJOox7Bg',
    appId: '1:981176022677:web:8f127b905462fe020b8d9c',
    messagingSenderId: '981176022677',
    projectId: 'tripgenie-project-finki',
    authDomain: 'tripgenie-project-finki.firebaseapp.com',
    storageBucket: 'tripgenie-project-finki.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0yykfmDCuD8m4v_6GqBBvZKTesMeCVHU',
    appId: '1:981176022677:android:47f90eecb64518690b8d9c',
    messagingSenderId: '981176022677',
    projectId: 'tripgenie-project-finki',
    storageBucket: 'tripgenie-project-finki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjX30dyD8M0sLL5AV8taAfftxzy22d8Gw',
    appId: '1:981176022677:ios:38571fa0b23d6b860b8d9c',
    messagingSenderId: '981176022677',
    projectId: 'tripgenie-project-finki',
    storageBucket: 'tripgenie-project-finki.firebasestorage.app',
    iosBundleId: 'com.example.tripGenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjX30dyD8M0sLL5AV8taAfftxzy22d8Gw',
    appId: '1:981176022677:ios:38571fa0b23d6b860b8d9c',
    messagingSenderId: '981176022677',
    projectId: 'tripgenie-project-finki',
    storageBucket: 'tripgenie-project-finki.firebasestorage.app',
    iosBundleId: 'com.example.tripGenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvWT-UqCOK_JCnu0VCsNihgcIMJOox7Bg',
    appId: '1:981176022677:web:7d70f3224f1a7db10b8d9c',
    messagingSenderId: '981176022677',
    projectId: 'tripgenie-project-finki',
    authDomain: 'tripgenie-project-finki.firebaseapp.com',
    storageBucket: 'tripgenie-project-finki.firebasestorage.app',
  );
}
